# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np
from initialise import answer

In [3]:
answer(1)

import numpy as np


#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
print(np.__version__)
np.show_config()

2.0.0
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30154",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.10",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30154",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.27",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-zh8sc4vi/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include",
      "lib 

d:\CS-IT\VS Workspaces\1 - Github Fork\100-numpy-exercises\.venv\Lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


In [5]:
answer(2)

print(np.__version__)
np.show_config()


#### 3. Create a null vector of size 10 (★☆☆)

In [6]:
v = np.zeros(10)
v

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
answer(3)

Z = np.zeros(10)
print(Z)


#### 4. How to find the memory size of any array (★☆☆)

In [8]:
v.size * v.itemsize

80

In [9]:
answer(4)

Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [10]:
np.info("add")

     *** Found in numpy ***
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via t

In [11]:
answer(5)

%run `python -c "import numpy; numpy.info(numpy.add)"`


#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [12]:
v = np.zeros(10)
v[4] = 10
v

array([ 0.,  0.,  0.,  0., 10.,  0.,  0.,  0.,  0.,  0.])

In [13]:
answer(6)

Z = np.zeros(10)
Z[4] = 1
print(Z)


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [14]:
v = np.arange(10, 50)
v

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [15]:
answer(7)

Z = np.arange(10,50)
print(Z)


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [16]:
v = v[::-1]
v

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [17]:
answer(8)

Z = np.arange(50)
Z = Z[::-1]
print(Z)


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [18]:
v = np.arange(0, 9).reshape(3, 3)
v

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
answer(9)

Z = np.arange(9).reshape(3, 3)
print(Z)


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [20]:
v = np.array([1, 2, 0, 0, 4, 0])
np.nonzero(v)

(array([0, 1, 4]),)

In [21]:
answer(10)

nz = np.nonzero([1,2,0,0,4,0])
print(nz)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [22]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
answer(11)

Z = np.eye(3)
print(Z)


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [24]:
v = np.random.randint(10, size=(3, 3, 3))
v

array([[[3, 7, 9],
        [8, 4, 3],
        [8, 0, 4]],

       [[7, 0, 4],
        [7, 9, 7],
        [4, 2, 3]],

       [[0, 2, 6],
        [9, 3, 4],
        [9, 3, 7]]], dtype=int32)

In [25]:
answer(12)

Z = np.random.random((3,3,3))
print(Z)


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [26]:
v = np.random.randint(1000, size=(10, 10))
print(v)

print(v.max())
print(v.min())

[[424 479 242  85  47 892 877 988 718 435]
 [ 84 731 962 619 874 593 927 901 796 164]
 [438 497 100 206  15 355 353 716 979 501]
 [483 355 718 133 339 287 731 279 359 230]
 [443 847 695 437 948 148 938 921 123 587]
 [360 783  57 336  42 669 523 728 741 900]
 [362 281 934  95  59 324 532 558 919 938]
 [700 448 511 558 121 991 502 494 976 240]
 [873 211 434 649 331 393 265 495   3 632]
 [707 191 538 125  94 605 890 222 465 926]]
991
3


In [27]:
answer(13)

Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [28]:
v = np.random.randint(100, size=30)
print(v)

v.mean()

[89 18 90 81 57 31 94 97 87 90 76  8 12 26 45 88 96 26 84 84 17 48 59 24
 93 68 33 82 44 64]


np.float64(60.36666666666667)

In [29]:
answer(14)

Z = np.random.random(30)
m = Z.mean()
print(m)


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [30]:
v = np.ones((5, 5))
v[1:-1, 1:-1] = np.zeros((3, 3))
v

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [31]:
answer(15)

Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [32]:
v = np.random.randint(10, size=(5, 5))
print(v)

np.pad(v, (1, 1), "constant", constant_values=0)

[[2 3 8 7 6]
 [2 3 1 4 9]
 [0 9 0 1 8]
 [7 1 0 3 5]
 [3 4 7 5 8]]


array([[0, 0, 0, 0, 0, 0, 0],
       [0, 2, 3, 8, 7, 6, 0],
       [0, 2, 3, 1, 4, 9, 0],
       [0, 0, 9, 0, 1, 8, 0],
       [0, 7, 1, 0, 3, 5, 0],
       [0, 3, 4, 7, 5, 8, 0],
       [0, 0, 0, 0, 0, 0, 0]], dtype=int32)

In [33]:
answer(16)

Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

# Using fancy indexing
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [34]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [35]:
answer(17)

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [36]:
v = np.diag([1, 2, 3, 4], -1)
v

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [37]:
answer(18)

Z = np.diag(1+np.arange(4),k=-1)
print(Z)


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [38]:
v = np.zeros((8, 8), dtype="int")
v[::2, 1::2] = 1
v[1::2, ::2] = 1
v

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [39]:
answer(19)

Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [40]:
# return a tuple of the index of the nth+1 element
np.unravel_index(99, (6, 7, 8))

(np.int64(1), np.int64(5), np.int64(3))

In [41]:
answer(20)

print(np.unravel_index(99,(6,7,8)))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [42]:
np.tile([[0, 1], [1, 0]], (4, 4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [43]:
answer(21)

Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [44]:
v = np.random.randint(100, size=(5, 5))
print(v)

# L2 norm calculation
# Magnitude being the square root of the sum of the squared values
magnitude = np.sqrt((v**2).sum(axis=1))
v / magnitude.reshape(5, 1)

[[68 42  9 74 66]
 [65 95 44 75 69]
 [92 73 90 72 98]
 [15 73 69 69 34]
 [17 81  6 24 16]]


array([[0.53260077, 0.3289593 , 0.07049128, 0.57959495, 0.51693604],
       [0.40647235, 0.59407497, 0.27515051, 0.46900656, 0.43148603],
       [0.48036045, 0.38115558, 0.46991783, 0.37593427, 0.51168831],
       [0.11773491, 0.57297654, 0.54158057, 0.54158057, 0.26686579],
       [0.19350694, 0.92200363, 0.06829657, 0.27318626, 0.18212417]])

In [45]:
# Proof of the result above
from sklearn.preprocessing import normalize

# L2 norm is the default one
v_norm_l2 = normalize(v)
v_norm_l2

array([[0.53260077, 0.3289593 , 0.07049128, 0.57959495, 0.51693604],
       [0.40647235, 0.59407497, 0.27515051, 0.46900656, 0.43148603],
       [0.48036045, 0.38115558, 0.46991783, 0.37593427, 0.51168831],
       [0.11773491, 0.57297654, 0.54158057, 0.54158057, 0.26686579],
       [0.19350694, 0.92200363, 0.06829657, 0.27318626, 0.18212417]])

In [46]:
answer(22)

Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [47]:
color = np.dtype([("r", np.uint8), ("g", np.uint8), ("b", np.uint8), ("a", np.uint8)])

In [48]:
answer(23)

color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [49]:
mat_1 = np.random.randint(10, size=(5, 3))
mat_2 = np.random.randint(10, size=(3, 2))
print(mat_1)
print(mat_2)

v = mat_1.dot(mat_2)
v

[[6 4 1]
 [1 7 5]
 [1 1 6]
 [7 9 3]
 [1 5 9]]
[[4 0]
 [1 4]
 [8 9]]


array([[ 36,  25],
       [ 51,  73],
       [ 53,  58],
       [ 61,  63],
       [ 81, 101]], dtype=int32)

In [50]:
answer(24)

Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [51]:
v = np.random.randint(10, size=(10))
print(v)

np.where((v > 3) & (v < 8), -v, v)

[4 3 4 0 6 2 4 2 9 0]


array([-4,  3, -4,  0, -6,  2, -4,  2,  9,  0], dtype=int32)

In [52]:
answer(25)

# Author: Evgeni Burovski

Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [53]:
# The first use the python sum
# so -1 is added to the value and return 9
# The second use numpy sum because of the * import
# so -1 is for the axis argument and sum return 10
""" print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1)) """

' print(sum(range(5),-1))\nfrom numpy import *\nprint(sum(range(5),-1)) '

In [54]:
answer(26)

# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [55]:
Z = np.array([1, 2, 3, 4, 5])

print(Z**Z)
print(2 << Z >> 2)
print(Z < -Z)
print(1j * Z)
print(Z / 1 / 1)
# print(Z<Z>Z) Not legal

[   1    4   27  256 3125]
[ 1  2  4  8 16]
[False False False False False]
[0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j]
[1. 2. 3. 4. 5.]


In [56]:
answer(27)

Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [57]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


C:\Users\lambe\AppData\Local\Temp\ipykernel_15620\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\lambe\AppData\Local\Temp\ipykernel_15620\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\lambe\AppData\Local\Temp\ipykernel_15620\3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


In [58]:
answer(28)

print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [59]:
v = np.array([-0.8, -0.5, -0.2, 0.0, 1.2, 1.5, 1.7])
print(v)

np.where(v > 0, np.ceil(v), np.floor(v))

[-0.8 -0.5 -0.2  0.   1.2  1.5  1.7]


array([-1., -1., -1.,  0.,  2.,  2.,  2.])

In [60]:
answer(29)

# Author: Charles R Harris

Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))


#### 30. How to find common values between two arrays? (★☆☆)

In [61]:
v1 = np.random.randint(10, size=10)
v2 = np.random.randint(10, size=10)
print(v1)
print(v2)

np.intersect1d(v1, v2)

[1 0 0 5 1 0 7 2 3 9]
[3 8 9 7 8 9 6 6 7 8]


array([3, 7, 9], dtype=int32)

In [62]:
answer(30)

Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [63]:
# np.seterr(all="ignore")
Z = np.ones(1) / 0

C:\Users\lambe\AppData\Local\Temp\ipykernel_15620\43861067.py:2: RuntimeWarning: divide by zero encountered in divide
  Z = np.ones(1) / 0


In [64]:
answer(31)

# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [65]:
# sqrt return nan
# and emath.sqrt return the complex number 1j
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\lambe\AppData\Local\Temp\ipykernel_15620\1701258291.py:3: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

In [66]:
answer(32)

np.sqrt(-1) == np.emath.sqrt(-1)


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [67]:
print(np.datetime64("today"))
print(np.datetime64("today") + np.timedelta64(-1, "D"))
print(np.datetime64("today") + np.timedelta64(1, "D"))

2024-07-26
2024-07-25
2024-07-27


In [68]:
answer(33)

yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [69]:
# hint fail because it gives np.arange(dtype=datetime64['D'])
# instead of np.arange(dtype='datetime64[D]')
v = np.arange("2016-07-01", "2016-08-01", dtype="datetime64[D]")
v

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [70]:
answer(34)

Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [71]:
A = np.array(np.random.rand(10) * 10 // 1)
B = np.array(np.random.rand(10) * 10 // 1)
print(A)
print(B)

np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)
A

[6. 8. 8. 2. 0. 0. 5. 5. 8. 4.]
[2. 6. 4. 3. 4. 1. 8. 1. 6. 2.]


array([-24. , -56. , -48. ,  -5. ,  -0. ,  -0. , -32.5, -15. , -56. ,
       -12. ])

In [72]:
answer(35)

A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [73]:
v = np.array(np.random.rand(10) * 10)
print(v)

print(v - (v % 1))
print(v // 1)
print(np.floor(v))
print(np.trunc(v))
print(v.astype(int))

[6.82196083 4.02720725 9.65493029 0.52483606 8.93779542 9.84897422
 4.96027731 8.17288523 2.44102999 4.65943602]
[6. 4. 9. 0. 8. 9. 4. 8. 2. 4.]
[6. 4. 9. 0. 8. 9. 4. 8. 2. 4.]
[6. 4. 9. 0. 8. 9. 4. 8. 2. 4.]
[6. 4. 9. 0. 8. 9. 4. 8. 2. 4.]
[6 4 9 0 8 9 4 8 2 4]


In [74]:
answer(36)

Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [75]:
v = np.arange(0, 5)
v = np.tile(v, 5)
v.reshape(5, 5)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [76]:
answer(37)

Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

# without broadcasting
Z = np.tile(np.arange(0, 5), (5,1))
print(Z)


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [77]:
def iterable(x=10):
    for i in range(1, x + 1):
        yield i


v = np.fromiter(iterable(), dtype=int)
v

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
answer(38)

def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [79]:
v = np.linspace(0, 1, 11, endpoint=False)[1:]
v

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [80]:
answer(39)

Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [81]:
v = np.random.randint(0, 100, 10)
print(v)

v.sort()
v

[39 87 55 49 60 79 97  7  9 11]


array([ 7,  9, 11, 39, 49, 55, 60, 79, 87, 97], dtype=int32)

In [82]:
answer(40)

Z = np.random.random(10)
Z.sort()
print(Z)


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [83]:
v = np.random.randint(0, 10, 5)
print(v)

np.add.reduce(v)

[0 1 7 8 7]


np.int64(23)

In [84]:
answer(41)

# Author: Evgeni Burovski

Z = np.arange(10)
np.add.reduce(Z)


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [85]:
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)
print(A)
print(B)

equal = np.allclose(A, B)
print(equal)

[0 0 0 0 0]
[1 1 0 1 1]
False


In [86]:
answer(42)

A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)


#### 43. Make an array immutable (read-only) (★★☆)

In [87]:
v = np.random.randint(0, 10, 5)
v.flags.writeable = False
print(v)

# v[0] = 100

[0 2 3 1 0]


In [88]:
answer(43)

Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [89]:
v = np.random.randint(-10, 10, size=(10, 2))
print(v)

r = np.sqrt(v[:, 0] ** 2 + v[:, 1] ** 2)
print(r)
phi = np.arctan2(v[:, 1], v[:, 0])
print(phi)

[[  6   9]
 [  2  -9]
 [  8  -9]
 [  0 -10]
 [ -9  -5]
 [-10   8]
 [ -1  -2]
 [ -9   7]
 [  5   1]
 [ -5  -9]]
[10.81665383  9.21954446 12.04159458 10.         10.29563014 12.80624847
  2.23606798 11.40175425  5.09901951 10.29563014]
[ 0.98279372 -1.35212738 -0.84415399 -1.57079633 -2.63449415  2.46685171
 -2.03444394  2.48054948  0.19739556 -2.07789483]


In [90]:
answer(44)

Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [91]:
v = np.random.randint(0, 100, size=10)
print(v)

v[v.argmax()] = 0
v

[96 56 65 13 40 93 28 39 45 83]


array([ 0, 56, 65, 13, 40, 93, 28, 39, 45, 83], dtype=int32)

In [92]:
answer(45)

Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [93]:
grid_size = 5

x = np.linspace(0, 1, grid_size)
y = np.linspace(0, 1, grid_size)
print(x)
print(y)

v = np.zeros((5, 5), dtype=[("x", float), ("y", float)])
v["x"], v["y"] = np.meshgrid(x, y)
print(v)

[0.   0.25 0.5  0.75 1.  ]
[0.   0.25 0.5  0.75 1.  ]
[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [94]:
answer(46)

Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [95]:
""" A Cauchy matrix is a matrix determined by two vectors (arrays of numbers).
Given two vectors x and y, the Cauchy matrix C generated by them
is defined entry-wise as C[i][j] := 1/(x[i] - y[j]) """

x = np.arange(5)
# To be sure that x[i] != y[i]
y = x + 0.5
print(x)
print(y)

print("Using broadcasting:")
print(1.0 / (x.reshape((-1, 1)) - y))
print("Without the copy made by reshape:")
print(1.0 / (x[:, np.newaxis] - y))

[0 1 2 3 4]
[0.5 1.5 2.5 3.5 4.5]
Using broadcasting:
[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4       ]
 [ 0.4         0.66666667  2.         -2.         -0.66666667]
 [ 0.28571429  0.4         0.66666667  2.         -2.        ]]
Without the copy made by reshape:
[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4       ]
 [ 0.4         0.66666667  2.         -2.         -0.66666667]
 [ 0.28571429  0.4         0.66666667  2.         -2.        ]]


In [96]:
answer(47)

# Author: Evgeni Burovski

X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [97]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [98]:
answer(48)

for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)


#### 49. How to print all the values of an array? (★★☆)

In [99]:
np.set_printoptions(threshold=float("inf"))
v = np.zeros((40, 40))
print(v)

# Reset to default value
np.set_printoptions(threshold=1000)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [100]:
answer(49)

np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [101]:
v = np.random.randint(50, size=10)
scalar = np.random.randint(50)
print(v)
print(scalar)

dist = v - scalar
dist = np.abs(dist)
v[dist.argmin()]

[13 35 15 43 20 42 37 27 31 42]
0


np.int32(13)

In [102]:
answer(50)

Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [103]:
v = np.zeros(
    5,
    [
        ("position", [("x", float), ("y", float)]),
        ("color", [("r", int), ("g", int), ("b", int)]),
    ],
)
v

array([((0., 0.), (0, 0, 0)), ((0., 0.), (0, 0, 0)),
       ((0., 0.), (0, 0, 0)), ((0., 0.), (0, 0, 0)),
       ((0., 0.), (0, 0, 0))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<i8'), ('g', '<i8'), ('b', '<i8')])])

In [104]:
answer(51)

Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [105]:
# Had to check solution
# Substract itself by subtracting the transposition
Z = np.random.randint(10, size=(10, 2))
X, Y = np.atleast_2d(Z[:, 0], Z[:, 1])
D = np.sqrt((X - X.T) ** 2 + (Y - Y.T) ** 2) // 1
print(D)

[[0. 5. 5. 1. 6. 3. 3. 3. 4. 8.]
 [5. 0. 2. 4. 5. 2. 1. 2. 5. 3.]
 [5. 2. 0. 5. 3. 2. 3. 2. 7. 3.]
 [1. 4. 5. 0. 6. 3. 2. 3. 3. 7.]
 [6. 5. 3. 6. 0. 3. 5. 3. 8. 6.]
 [3. 2. 2. 3. 3. 0. 1. 0. 5. 5.]
 [3. 1. 3. 2. 5. 1. 0. 1. 4. 5.]
 [3. 2. 2. 3. 3. 0. 1. 0. 5. 5.]
 [4. 5. 7. 3. 8. 5. 4. 5. 0. 8.]
 [8. 3. 3. 7. 6. 5. 5. 5. 8. 0.]]


In [106]:
answer(52)

Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [107]:
v = np.random.rand(10).astype(np.float32)
print(f"id of v = {id(v)}")
u = v.view(np.int32)
print(f"id of u = {id(u)}")
v[:] = u
print(f"id of v = {id(v)}")

id of v = 2691321473488
id of u = 2691321475504
id of v = 2691321473488


In [108]:
answer(53)

# Thanks Vikas (https://stackoverflow.com/a/10622758/5989906)
# & unutbu (https://stackoverflow.com/a/4396247/5989906)
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [117]:
import io

file = io.StringIO(
    """ 
    1, 2, 3, 4, 5
    6,  ,  , 7, 8
    ,  , 9,10,11
    """
)

np.genfromtxt(file, dtype=np.int32, delimiter=",")

array([[ 1,  2,  3,  4,  5],
       [ 6, -1, -1,  7,  8],
       [-1, -1,  9, 10, 11]], dtype=int32)

In [115]:
answer(54)

from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [129]:
v = np.arange(9).reshape(3, 3)
print(v)
# Solution 1
for index, value in np.ndenumerate(v):
    print(index, value)

print("")

# Solution 2
for index in np.ndindex(v.shape):
    print(index, v[index])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [119]:
answer(55)

Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [133]:
# Had to check answer for this one
# Create two 2D arrays ‘x’ and ‘y’ using np.meshgrid and np.linspace.
# np.linspace creates 10 evenly spaced points between -1 and 1 for both arrays.
X, Y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))

# Calculate the Euclidean distance from the origin (0,0)
# to each coordinate in the grid using the Pythagorean theorem.

D = np.sqrt(X * X + Y * Y)
# Define the standard deviation sigma and the mean mu of the Gaussian function.
sigma, mu = 1.0, 0.0

# This line computes the Gaussian function values for each distance d
# using the given sigma and mu.
# This generates a 2D Gaussian-like array,
# where the values represent the amplitude of the Gaussian function
# at each grid point.
G = np.exp(-((D - mu) ** 2 / (2.0 * sigma**2)))
print(G)

[[-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]


In [131]:
answer(56)

X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [170]:
p = 5
element = 99
# Create the 2D array
v = np.zeros((5, 5))
# Create randomly an array of p number of different indices
idx = np.random.choice(range(25), p, replace=False)
print(idx)
# Get the coordinates of the indices above
x, y = np.unravel_index(idx, (5, 5))
# Place the elements
v[x, y] = element
v

[20 10  4  9 15]


array([[ 0.,  0.,  0.,  0., 99.],
       [ 0.,  0.,  0.,  0., 99.],
       [99.,  0.,  0.,  0.,  0.],
       [99.,  0.,  0.,  0.,  0.],
       [99.,  0.,  0.,  0.,  0.]])

In [141]:
answer(57)

# Author: Divakar

n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [206]:
v = np.random.rand(5, 4) * 100 // 1
print(v)

means = v.mean(axis=1)
print(means)
means = means.reshape(1, -1)
u = v - means.T
u

[[76. 21. 28. 38.]
 [96. 59. 52. 48.]
 [98. 66. 32. 21.]
 [ 2. 89. 46. 24.]
 [24. 74.  5. 46.]]
[40.75 63.75 54.25 40.25 37.25]


array([[ 35.25, -19.75, -12.75,  -2.75],
       [ 32.25,  -4.75, -11.75, -15.75],
       [ 43.75,  11.75, -22.25, -33.25],
       [-38.25,  48.75,   5.75, -16.25],
       [-13.25,  36.75, -32.25,   8.75]])

In [200]:
answer(58)

# Author: Warren Weckesser

X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)


#### 59. How to sort an array by the nth column? (★★☆)

In [242]:
v = np.random.randint(0, 100, size=(5, 4))
print(v)

n = 1
print(v[v[:, n].argsort()])

# Alternate syntax
idx = np.argsort(v, axis=0)
print(v[idx[:, n]])

[[69 18 27 16]
 [73  3 76 50]
 [77 35 99 81]
 [ 0 76 41 91]
 [14 88 88  2]]
[[73  3 76 50]
 [69 18 27 16]
 [77 35 99 81]
 [ 0 76 41 91]
 [14 88 88  2]]
[[73  3 76 50]
 [69 18 27 16]
 [77 35 99 81]
 [ 0 76 41 91]
 [14 88 88  2]]


In [211]:
answer(59)

# Author: Steve Tjoa

Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [294]:
# v = np.random.randint(0, 10, size=(5, 4))
v = np.array([[0, 1, np.nan], [1, 2, np.nan], [4, 5, np.nan], [7, 8, np.nan]])
print(v)

# If True the column is all null
print(np.any(np.all(np.isnan(v), axis=0)))
# If True the column is all zero
print((~Z.any(axis=0)).any())

[[ 0.  1. nan]
 [ 1.  2. nan]
 [ 4.  5. nan]
 [ 7.  8. nan]]
True
False


In [256]:
answer(60)

# Author: Warren Weckesser

# null : 0 
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

# null : np.nan
Z=np.array([
    [0,1,np.nan],
    [1,2,np.nan],
    [4,5,np.nan]
])
print(np.isnan(Z).all(axis=0))


#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)